from __future__ import annotations

from .compiler import CompilationResult


def _number(value: float) -> str:
    return f"{value:.2f}".rstrip("0").rstrip(".")


def render_markdown(result: CompilationResult) -> str:
    project = result.project
    pack = result.pack
    metrics = result.metrics
    routing = result.routing_stats
    errors = sum(item.severity == "error" for item in result.diagnostics)
    warnings = sum(item.severity == "warning" for item in result.diagnostics)
    status = "PASS" if errors == 0 else "FAIL"
    core_equivalents = (
        f"{routing.observed_core_equivalents:.2f}"
        if routing.observed_core_equivalents is not None
        else "n/a (sample too short)"
    )

    lines = [
        f"# {project.name}",
        "",
        "> Generated by Endfield Factory Compiler. "
        "Rates are expressed per minute.",
        "",
        "## Summary",
        "",
        "| Metric | Value |",
        "| --- | ---: |",
        f"| DRC | **{status}** ({errors} errors, {warnings} warnings) |",
        f"| Region pack | `{pack.id}` {pack.version} |",
        f"| Devices | {metrics.device_count} |",
        f"| Device footprint | {metrics.device_tiles} tiles |",
        f"| Logistics routes | {metrics.route_count} |",
        f"| Unique route tiles | {metrics.route_tiles} |",
        f"| Total routed length | {metrics.total_route_length} tiles |",
        f"| Route bends | {metrics.route_bends} |",
        f"| Crossing tiles | {metrics.crossing_tiles} |",
        f"| Router | `{routing.backend_name}` |",
        f"| Router jobs | {routing.effective_jobs} / "
        f"{routing.requested_jobs} effective/requested |",
        f"| A* expanded states | {routing.expanded_states} |",
        f"| Peak A* frontier | {routing.peak_frontier} |",
        f"| Routing time | {routing.elapsed_seconds * 1000:.2f} ms |",
        f"| Routing CPU time | {routing.cpu_seconds * 1000:.2f} ms |",
        f"| Observed core equivalents | {core_equivalents} |",
        f"| Area utilization | {metrics.area_utilization_percent:.1f}% |",
        f"| Power | {_number(result.synthesis.total_power)} / "
        f"{_number(pack.grid.max_power)} |",
        "",
        "## Targets",
        "",
        "| Item | Required rate |",
        "| --- | ---: |",
    ]
    for item, rate in sorted(project.targets.items()):
        lines.append(f"| {pack.items.get(item, item)} | {_number(rate)}/min |")

    lines.extend(
        [
            "",
            "## Production",
            "",
            "| Recipe | Machines | Required | Available | Power |",
            "| --- | ---: | ---: | ---: | ---: |",
        ]
    )
    for node in result.synthesis.nodes:
        recipe = pack.recipes[node.recipe_id]
        lines.append(
            f"| {recipe.name} | {node.machine_count} | "
            f"{_number(node.required_rate)}/min | "
            f"{_number(node.capacity_rate)}/min | {_number(node.power)} |"
        )

    lines.extend(
        [
            "",
            "## Raw inputs",
            "",
            "| Item | Required rate |",
            "| --- | ---: |",
        ]
    )
    for item, rate in result.synthesis.source_rates.items():
        lines.append(f"| {pack.items.get(item, item)} | {_number(rate)}/min |")

    constraints = project.constraints
    if any(
        value is not None
        for value in (
            constraints.max_power,
            constraints.max_devices,
            constraints.max_route_tiles,
        )
    ):
        lines.extend(
            [
                "",
                "## Project constraints",
                "",
                "| Constraint | Limit | Actual |",
                "| --- | ---: | ---: |",
            ]
        )
        if constraints.max_power is not None:
            lines.append(
                f"| Power | {_number(constraints.max_power)} | "
                f"{_number(result.synthesis.total_power)} |"
            )
        if constraints.max_devices is not None:
            lines.append(
                f"| Devices | {constraints.max_devices} | "
                f"{metrics.device_count} |"
            )
        if constraints.max_route_tiles is not None:
            lines.append(
                f"| Route tiles | {constraints.max_route_tiles} | "
                f"{metrics.route_tiles} |"
            )

    lines.extend(["", "## Diagnostics", ""])
    for diagnostic in result.diagnostics:
        marker = {
            "error": "[ERROR]",
            "warning": "[WARN]",
            "info": "[INFO]",
        }.get(diagnostic.severity, "[NOTE]")
        lines.append(
            f"- {marker} `{diagnostic.code}` - {diagnostic.message}"
        )
    lines.append("")
    return "\n".join(lines)
